### ISSUE TITLE
Step 3 (Collection) is broken on running `meteor add react-meteor-data`

### ISSUE THREAD

**Issue by hassan-me** [meteor/simple-todos-react#61] opened 2018-01-27 08:14 UTC
I have been playing around with todo-react tutorial of meteor. It seems the tutorial is broken at Step 3. Everything works till `meteor add react-meteor-data` 

It gives the following error

`
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at checkNpmVersions (check-npm-versions.js:25)
    at react-meteor-data.jsx (react-meteor-data.jsx:3)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at react-meteor-data.js?hash=5b748cb382c95061d60866039fbe5bfcf8eb10b3:398
    at react-meteor-data.js?hash=5b748cb382c95061d60866039fbe5bfcf8eb10b3:405
`

`
Uncaught TypeError: Cannot read property 'ReactMeteorData' of undefined
    at global-imports.js?hash=854d4c2aa7a66a124a83cdb82c644bad3f28bd25:7
(anonymous) @ global-imports.js?hash=854d4c2aa7a66a124a83cdb82c644bad3f28bd25:7
`

`
Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=49773ab8dd805ae250bcd0ffa01ca18dc627fde5:1
`

Any help in given context would be appreciated.

**Comment by hwillson** [comment] 2018-01-27 12:33
Hi @hassan-me - this is a known issue with the `react-meteor-data` package, and has been fixed in https://github.com/meteor/react-packages/pull/247. We'll have a new version published soon, at which point you'll be able to run `meteor update react-meteor-data` to fix the issue. I'll post back when the new version is ready. Thanks, and sorry for the inconvenience!

**Comment by abernix** [comment] 2018-01-31 10:13
This should be resolved with the latest fix to `react-meteor-data`, which has been published in `react-meteor-data@0.2.16`.  Please try again and let us know if the problem is resolved.

And thank you so much for raising this issue in the first place—it truly helps!

**Closed as completed by abernix** 2018-01-31 10:13 UTC

**Comment by hassan-me** [comment] 2018-02-23 11:52
@abernix, @hwillson
Hey guys, just ran it now. Bingo! Its no longer broken :)
Thanks a lot for pushing the fix and sorry for late response.
